apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitjsclock-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitjsclock
  template:
    metadata:
      labels:
        app: gitjsclock
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-node  # replace with exact name from `kubectl get nodes`
      containers:
        - name: gitjsclock
          image: priyabratakhandual/gitjsclock:latest
          ports:
            - containerPort: 80
